"""RCM chat orchestration.

    question -> intent -> grounding (RAG / analytics) -> grounded prompt -> local SLM
             -> validation -> (regenerate with stronger grounding) -> (validated fallback)
             -> (mask unverified identifiers) -> answer

The service never fabricates an answer: every non-guardrail response is generated by the
configured LLMProvider. The only deterministic text paths are (a) greeting/out-of-scope
guardrails, which make no factual claims, and (b) the validated-definition fallback, which
returns knowledge-base text verbatim when the model contradicts it twice.
"""

from __future__ import annotations

import json
import logging
import time
from collections.abc import Iterator
from dataclasses import dataclass, field
from typing import Protocol

from starlette.concurrency import run_in_threadpool

from app.ai import prompts
from app.ai.intent import Intent, IntentResult, classify
from app.ai.llm_provider import ChatMessage, GenerationParams, LLMProvider, LLMResult
from app.ai.postprocess import clean_answer
from app.ai.prompts import ContextBlock
from app.ai.rag import retrieve_context
from app.ai.validators import ResponseValidator, ValidationIssue, ValidationReport, redact_identifiers
from app.core.config import Settings
from app.rag.base import KnowledgeRetriever, RetrievedChunk
from app.schemas.chat import (
    ChatRequest,
    ChatResponse,
    IntentOut,
    SourceOut,
    UsageOut,
    ValidationIssueOut,
    ValidationOut,
)

logger = logging.getLogger(__name__)

# Below this top retrieval score (cross-encoder probability) a query with no RCM vocabulary
# is treated as out of scope.
MIN_RELEVANCE_FOR_UNKNOWN = 0.2


@dataclass
class DataContext:
    """Deterministically computed figures handed to the model (Phase 4/5)."""

    text: str
    payload: dict = field(default_factory=dict)
    # Knowledge-base query built from the data itself (e.g. a claim's CARC and status), used
    # instead of the question wording so retrieval matches the specific situation.
    retrieval_query: str | None = None


class DataContextProvider(Protocol):
    def build(self, intent: IntentResult, question: str) -> DataContext | None: ...


@dataclass
class _Grounding:
    references: list[RetrievedChunk]
    data: DataContext | None


@dataclass
class _Draft:
    text: str
    result: LLMResult | None
    report: ValidationReport
    regenerated: bool = False
    fallback: bool = False
    pinned: list[ContextBlock] = field(default_factory=list)  # validated definitions added on repair


class ChatService:
    def __init__(
        self,
        llm: LLMProvider,
        settings: Settings,
        retriever: KnowledgeRetriever | None = None,
        data_provider: DataContextProvider | None = None,
        validator: ResponseValidator | None = None,
    ) -> None:
        self.llm = llm
        self.settings = settings
        self.retriever = retriever
        self.data_provider = data_provider
        self.validator = validator or ResponseValidator()

    # ------------------------------------------------------------------ public API
    async def answer(self, req: ChatRequest) -> ChatResponse:
        timings: dict[str, float] = {}
        t0 = time.perf_counter()
        intent = classify(req.message)
        timings["intent"] = _ms(t0)

        canned = self._guardrail_reply(intent)
        if canned:
            return self._response(canned, intent, [], ValidationReport(), False, None, timings, grounded=False)

        t = time.perf_counter()
        grounding = await run_in_threadpool(self._ground, intent, req)
        timings["retrieval"] = _ms(t)
        if self._out_of_scope_by_retrieval(intent, grounding):
            return self._response(prompts.OUT_OF_SCOPE_REPLY, intent, [], ValidationReport(), False, None, timings, grounded=False)

        t = time.perf_counter()
        draft = await run_in_threadpool(self._generate_validated, req, intent, grounding)
        timings["generation"] = _ms(t)
        timings["total"] = _ms(t0)

        logger.info(
            "chat intent=%s refs=%d data=%s regenerated=%s fallback=%s passed=%s gen_ms=%.0f",
            intent.intent.value, len(grounding.references), grounding.data is not None,
            draft.regenerated, draft.fallback, draft.report.passed, timings["generation"],
        )
        resp = self._response(
            draft.text, intent, grounding.references, draft.report, draft.regenerated, draft.result, timings,
            grounded=bool(grounding.references or grounding.data or draft.pinned), pinned=draft.pinned,
        )
        resp.data = grounding.data.payload if grounding.data else None
        return resp

    def stream_events(self, req: ChatRequest) -> Iterator[str]:
        """Server-sent events: `meta`, many `token`, optional `replace`, then `done`.

        Runs synchronously; Starlette iterates it in a worker thread.
        """
        t0 = time.perf_counter()
        intent = classify(req.message)
        canned = self._guardrail_reply(intent)
        grounding = _Grounding([], None) if canned else self._ground(intent, req)
        if not canned and self._out_of_scope_by_retrieval(intent, grounding):
            canned = prompts.OUT_OF_SCOPE_REPLY

        yield _sse("meta", {
            "intent": _intent_out(intent).model_dump(),
            "sources": [s.model_dump() for s in _sources_out(grounding.references)],
            "grounded": bool(grounding.references or grounding.data),
            "model": None if canned else self.llm.info().name,
            "data": grounding.data.payload if grounding.data else None,
        })
        if canned:
            yield _sse("token", {"text": canned})
            yield _sse("done", {"validation": ValidationOut(passed=True).model_dump(), "timings_ms": {"total": _ms(t0)}})
            return

        messages = self._messages(req, grounding)
        params = self._params(req)
        parts: list[str] = []
        in_think = False
        for delta in self.llm.stream(messages, params):
            parts.append(delta)
            # Hide any reasoning block if thinking is enabled on the provider.
            if "<think>" in delta:
                in_think = True
            if in_think:
                if "</think>" in delta:
                    in_think = False
                continue
            yield _sse("token", {"text": delta})

        streamed = _strip_think("".join(parts))
        cleaned = clean_answer(streamed, req.message)
        report = self._validate(cleaned, req.message, intent, grounding, "stop")
        final = _Draft(cleaned, None, report)
        if not report.passed:
            final = self._mask_identifiers(req, grounding, self._repair(req, intent, grounding, final))
        if final.text != streamed:
            yield _sse("replace", {
                "text": final.text,
                "reason": report.correction_hint() or "cleaned formatting",
                "sources": [s.model_dump() for s in _sources_out(grounding.references, final.pinned)],
            })
        yield _sse("done", {
            "validation": _validation_out(final.report, final.regenerated).model_dump(),
            "timings_ms": {"total": _ms(t0)},
        })

    # ------------------------------------------------------------------ pipeline steps
    def _guardrail_reply(self, intent: IntentResult) -> str | None:
        if intent.intent == Intent.GREETING:
            return prompts.GREETING_REPLY
        if intent.intent == Intent.OUT_OF_SCOPE:
            return prompts.OUT_OF_SCOPE_REPLY
        return None

    def _ground(self, intent: IntentResult, req: ChatRequest) -> _Grounding:
        data = None
        if self.data_provider is not None and _is_data_intent(intent):
            data = self.data_provider.build(intent, req.message)
        refs: list[RetrievedChunk] = []
        if req.options.use_rag:
            # Data questions already carry a fact sheet; keep the knowledge context small (CPU prompt cost).
            k = 2 if data else self.settings.rag_top_k
            # "Why was CLM-001234 denied?" says nothing about *why*; the claim's CARC and status do.
            # Pinned definitions still follow the question's own terms, so they don't crowd out
            # the situation-specific passages in the small data-question context.
            query = data.retrieval_query if data and data.retrieval_query else req.message
            refs = retrieve_context(self.retriever, query, k=k, terms=intent.terms)
        return _Grounding(refs, data)

    def _out_of_scope_by_retrieval(self, intent: IntentResult, g: _Grounding) -> bool:
        # A query with no RCM vocabulary is only answered if the knowledge base finds it relevant.
        if intent.confidence >= 0.5 or self.retriever is None or not self.retriever.is_ready():
            return False
        top = max((r.score for r in g.references), default=0.0)
        return top < MIN_RELEVANCE_FOR_UNKNOWN and g.data is None

    def _params(self, req: ChatRequest) -> GenerationParams:
        s = self.settings
        return GenerationParams(
            max_tokens=req.options.max_tokens or s.llm_max_tokens,
            temperature=s.llm_temperature if req.options.temperature is None else req.options.temperature,
            top_p=s.llm_top_p,
            top_k=s.llm_top_k,
            repeat_penalty=s.llm_repeat_penalty,
        )

    def _messages(self, req: ChatRequest, g: _Grounding, extra_refs: list[ContextBlock] | None = None,
                  correction: str | None = None) -> list[ChatMessage]:
        history = [ChatMessage(h.role, h.content) for h in req.history[-2 * self.settings.chat_max_history_turns:]]
        blocks = [ContextBlock(i + 1, _ref_title(r), r.chunk.text) for i, r in enumerate(g.references)]
        # Extra (pinned) references are numbered after the retrieved ones so citations stay stable.
        blocks += [ContextBlock(len(blocks) + i + 1, b.title, b.text) for i, b in enumerate(extra_refs or [])]
        return prompts.build_messages(
            req.message, history=history, references=blocks or None,
            data_context=g.data.text if g.data else None, correction=correction,
            format_instructions=prompts.FORMAT_ANALYTICS if g.data else prompts.FORMAT_KNOWLEDGE,
        )

    def _validate(self, text: str, question: str, intent: IntentResult, g: _Grounding, finish: str) -> ValidationReport:
        return self.validator.validate(
            text, question, intent.terms,
            reference_texts=[r.chunk.text for r in g.references],
            data_text=g.data.text if g.data else None,
            finish_reason=finish,
        )

    def _generate_validated(self, req: ChatRequest, intent: IntentResult, g: _Grounding) -> _Draft:
        result = self.llm.generate(self._messages(req, g), self._params(req))
        result.text = clean_answer(result.text, req.message)
        report = self._validate(result.text, req.message, intent, g, result.finish_reason)
        draft = _Draft(result.text, result, report)
        return draft if report.passed else self._mask_identifiers(req, g, self._repair(req, intent, g, draft))

    def _repair(self, req: ChatRequest, intent: IntentResult, g: _Grounding, draft: _Draft) -> _Draft:
        """One regeneration with validated definitions pinned first, then a verbatim fallback."""
        rules = self.validator.term_rules
        term_keys = {i.term for i in draft.report.term_errors} | set(intent.terms)
        pinned = [ContextBlock(0, f"Validated definition: {rules[k].name}", rules[k].definition)
                  for k in sorted(term_keys) if k in rules]
        messages = self._messages(req, g, extra_refs=pinned, correction=draft.report.correction_hint())
        params = self._params(req)
        params = GenerationParams(**{**params.__dict__, "temperature": min(params.temperature, 0.1)})
        result = self.llm.generate(messages, params)
        result.text = clean_answer(result.text, req.message)
        refs_text = [r.chunk.text for r in g.references] + [b.text for b in pinned]
        report = self.validator.validate(result.text, req.message, intent.terms, refs_text,
                                         g.data.text if g.data else None, result.finish_reason)
        # Keep the rejected draft's errors visible: they explain why the answer was regenerated.
        report.issues[:0] = [
            ValidationIssue(f"draft_{i.code}", "info", f"Initial draft rejected: {i.message}")
            for i in draft.report.issues if i.severity == "error"
        ]
        if report.passed:
            return _Draft(result.text, result, report, regenerated=True, pinned=pinned)

        if report.term_errors and pinned and g.data is None:
            # Knowledge question where the model contradicted the knowledge base twice: return the
            # validated definitions verbatim. (Data answers are never replaced by a definition; their
            # remaining issues stay visible in the validation report instead.)
            body = "\n\n".join(f"**{b.title.removeprefix('Validated definition: ')}:** {b.text}" for b in pinned)
            text = ("The generated answer did not match the validated RCM definitions, so the knowledge-base "
                    f"definition is shown instead.\n\n{body}")
            report.issues.append(_fallback_issue())
            return _Draft(text, result, _strip_term_errors(report), regenerated=True, fallback=True, pinned=pinned)
        return _Draft(result.text, result, report, regenerated=True, pinned=pinned)

    @staticmethod
    def _mask_identifiers(req: ChatRequest, g: _Grounding, draft: _Draft) -> _Draft:
        """Last line of defence: an identifier the model invented even after regeneration is masked,
        never shown. The issue stays visible as a warning."""
        flagged = [i for i in draft.report.issues if i.code == "unsupported_identifier" and i.severity == "error"]
        if not flagged:
            return draft
        sources = [req.message, g.data.text if g.data else "",
                   *(r.chunk.text for r in g.references), *(b.text for b in draft.pinned)]
        draft.text = redact_identifiers(draft.text, sources)
        for i in flagged:
            i.severity = "warning"
            i.message = f"(masked in answer) {i.message}"
        return draft

    # ------------------------------------------------------------------ response assembly
    def _response(self, text: str, intent: IntentResult, refs: list[RetrievedChunk], report: ValidationReport,
                  regenerated: bool, result: LLMResult | None, timings: dict[str, float], grounded: bool,
                  pinned: list[ContextBlock] | None = None) -> ChatResponse:
        return ChatResponse(
            answer=text,
            intent=_intent_out(intent),
            sources=_sources_out(refs, pinned),
            validation=_validation_out(report, regenerated),
            grounded=grounded,
            model=result.model if result else None,
            usage=UsageOut(prompt_tokens=result.prompt_tokens, completion_tokens=result.completion_tokens) if result else UsageOut(),
            timings_ms=timings,
        )


# ---------------------------------------------------------------------- helpers
def _is_data_intent(intent: IntentResult) -> bool:
    return intent.intent in (Intent.KPI_ANALYTICS, Intent.CLAIM_SPECIFIC, Intent.DATA_QUERY)


def _ms(t: float) -> float:
    return round((time.perf_counter() - t) * 1000, 1)


def _sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


def _strip_think(text: str) -> str:
    from app.ai.local_llm import strip_reasoning

    return strip_reasoning(text)


def _ref_title(r: RetrievedChunk) -> str:
    return f"{r.chunk.title} - {r.chunk.section}" if r.chunk.section else r.chunk.title


def _intent_out(i: IntentResult) -> IntentOut:
    return IntentOut(intent=i.intent.value, confidence=round(i.confidence, 2), terms=i.terms, entities=i.entities)


def _snippet(text: str) -> str:
    return text[:280] + ("..." if len(text) > 280 else "")


def _sources_out(refs: list[RetrievedChunk], pinned: list[ContextBlock] | None = None) -> list[SourceOut]:
    out = [
        SourceOut(ref=i + 1, title=r.chunk.title, document=r.chunk.document, section=r.chunk.section,
                  score=round(r.score, 3), snippet=_snippet(r.chunk.text))
        for i, r in enumerate(refs)
    ]
    out += [
        SourceOut(ref=len(refs) + i + 1, title=b.title, document="validated_terms.yaml", section=None,
                  score=1.0, snippet=_snippet(b.text))
        for i, b in enumerate(pinned or [])
    ]
    return out


def _validation_out(report: ValidationReport, regenerated: bool) -> ValidationOut:
    return ValidationOut(
        passed=report.passed,
        regenerated=regenerated,
        issues=[ValidationIssueOut(code=i.code, severity=i.severity, message=i.message) for i in report.issues],
    )


def _fallback_issue() -> ValidationIssue:
    return ValidationIssue("validated_fallback", "warning",
                           "Model output contradicted validated definitions twice; returned the knowledge-base definition.")


def _strip_term_errors(report: ValidationReport) -> ValidationReport:
    # The fallback text is the validated definition itself, so the model's term errors no longer apply;
    # keep them visible as warnings for transparency.
    for i in report.issues:
        if i.severity == "error" and i.term:
            i.severity = "warning"
            i.message = f"(rejected draft) {i.message}"
    return report
