"""Build knowledge/curated_qa.md from the fine-tuning Q&A so the RAG layer can retrieve it.

The fine-tuned model saw only ~100 open RCM knowledge examples, too few to learn them reliably.
This turns those examples into a retrievable knowledge document, with three safeguards:

  - only open questions (empty `input`) from the knowledge categories; claim templates are skipped
  - questions that appear in the validation or test splits are excluded, so evaluation stays clean
  - every answer must pass the validated-terms checks (acronym expansions, forbidden
    misdefinitions, KPI formulas, invented identifiers); failing answers are dropped and listed

Usage (from backend/, after venv/Scripts/activate), then rebuild the index:
    python ../scripts/build_curated_qa.py
    python ../scripts/ingest_knowledge.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.ai.intent import detect_terms  # noqa: E402
from app.ai.validators import ResponseValidator  # noqa: E402

DATASETS = REPO_ROOT / "training" / "datasets"
# Earlier sources win when the same question appears twice: the anchor set is the curated one.
SOURCES = [DATASETS / "rcm_terminology_anchor.jsonl", DATASETS / "v2_1" / "train.jsonl"]
HOLDOUT = [DATASETS / "v2_1" / "validation.jsonl", DATASETS / "v2_1" / "test.jsonl"]
OUTPUT = REPO_ROOT / "knowledge" / "curated_qa.md"

# Category -> section heading, in output order.
CATEGORIES = {
    "rcm_knowledge": "RCM terminology",
    "comparison": "Comparisons",
    "kpi_analysis": "KPI interpretation",
    "rcm_general": "RCM processes",
    "rcm_reasoning": "RCM reasoning",
}

FRONTMATTER = """---
title: Curated RCM Q&A
category: curated_qa
source_basis: Curated question-answer pairs from the RCM fine-tuning set (v2.1 train and terminology anchor), checked against validated_terms.yaml. Generated by scripts/build_curated_qa.py - do not edit by hand.
---
"""


def _rows(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def _key(question: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", question.lower()).strip()


def collect() -> tuple[dict[str, list[tuple[str, str]]], list[str]]:
    holdout = {_key(r["instruction"]) for p in HOLDOUT for r in _rows(p)}
    validator = ResponseValidator()
    by_category: dict[str, list[tuple[str, str]]] = {c: [] for c in CATEGORIES}
    seen: set[str] = set()
    report: list[str] = []
    for path in SOURCES:
        for r in _rows(path):
            q, a, cat = r["instruction"].strip(), r["output"].strip(), r.get("category")
            k = _key(q)
            if cat not in CATEGORIES or r.get("input", "").strip() or k in seen:
                continue
            seen.add(k)
            if k in holdout:
                report.append(f"held out (in validation/test): {q}")
                continue
            rep = validator.validate(a, q, detect_terms(q))
            if not rep.passed:
                report.append(f"rejected ({rep.correction_hint()}): {q}")
                continue
            by_category[cat].append((q, a))
    return by_category, report


def render(by_category: dict[str, list[tuple[str, str]]]) -> str:
    parts = [FRONTMATTER, "# Curated RCM Q&A\n"]
    for cat, heading in CATEGORIES.items():
        if not by_category[cat]:
            continue
        parts.append(f"## {heading}\n")
        parts += [f"### {q}\n\n{a}\n" for q, a in by_category[cat]]
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    by_category, report = collect()
    args.output.write_text(render(by_category), encoding="utf-8", newline="\n")
    total = sum(len(v) for v in by_category.values())
    print(f"Wrote {total} Q&A pairs -> {args.output}")
    for cat, rows in by_category.items():
        print(f"  {CATEGORIES[cat]}: {len(rows)}")
    if report:
        print(f"\nSkipped {len(report)}:")
        for line in report:
            print(f"  - {line}")


if __name__ == "__main__":
    main()
